name = "ljoson-blog"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ljoson-blog-production"

[env.staging]
name = "ljoson-blog-staging"

# Pages配置
[pages]
# 构建命令
build.command = "npm run build"
# 输出目录
build.output_dir = "out"
# 环境变量
[pages.env]
NODE_VERSION = "18"

# 路由配置
[[pages.routes]]
pattern = "/*"
zone_name = "ljoson.com"
custom_domain = true

# 缓存配置
[pages.env.production.vars]
CACHE_CONTROL = "public, max-age=0, must-revalidate"

# 安全头配置
[[pages.headers]]
for = "/*"
[pages.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# 静态资源缓存配置
[[pages.headers]]
for = "*.js"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[pages.headers]]
for = "*.css"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[pages.headers]]
for = "*.html"
[pages.headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[pages.headers]]
for = "*.png"
[pages.headers.values]
Cache-Control = "public, max-age=86400"

[[pages.headers]]
for = "*.jpg"
[pages.headers.values]
Cache-Control = "public, max-age=86400"

[[pages.headers]]
for = "*.svg"
[pages.headers.values]
Cache-Control = "public, max-age=86400"

[[pages.headers]]
for = "*.woff2"
[pages.headers.values]
Cache-Control = "public, max-age=31536000"
